#dev
server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Data Source 설정
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/study
      driver-class-name: org.h2.Driver
      username: sa
      password:
#spring.datasource.hikari.jdbc-url=jdbc:h2:~/study
#spring.datasource.hikari.driver-class-name=org.h2.Driver
#spring.datasource.hikari.username=sa
#spring.datasource.hikari.password=

# JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      #ddl-auto 주의 주의 또 주의...! 
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto: create

# log 설정
logging:
  level:
    org:
      hibernate:
       SQL: debug
       type:
         descriptor:
           sql: trace
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

