#prod
server:
  port: 80

# H2 설정
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

# Data Source 설정
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/study
      driver-class-name: org.h2.Driver
      username: sa
      password:

# JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

# log 설정
logging:
  level:
    org:
      hibernate:
       SQL: debug
       type:
         descriptor:
           sql: trace

